<?php

/**
 * @file
 * Contains netforum_org_sync.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\netforum_org_sync\OrgSync;

/**
 * Implements hook_help().
 */
function netforum_org_sync_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the netforum_org_sync module.
    case 'help.page.netforum_org_sync':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Syncs both Facilities and Preferred Vendors from Mass Senior Care&#039;s NetForum account') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_cron().
 */
function netforum_org_sync_cron() {
  /** @var \Drupal\Core\State\StateInterface $state */
  $state = \Drupal::service('state');
  $last = strtotime('-3 weeks');
  try {
    $current_time = \Drupal::time()->getRequestTime();
    /** @var \Drupal\Core\Datetime\DateFormatterInterface $formatter */
    $formatter = \Drupal::service('date.formatter');
    $count = \Drupal::service(OrgSync::CRON_STATE_KEY)->syncOrganizationChanges($last, $current_time);
    $state->set(OrgSync::CRON_STATE_KEY, $current_time);
    \Drupal::logger('netforum_org_sync')->notice('Synced @count organization changes from @start to @end',
      ['@start' => $formatter->format($last), '@end' => $formatter->format($current_time), '@count' => $count]);
  }
  catch (Exception $exception) {
    watchdog_exception('netforum_org_sync', $exception, 'Unable to sync events during cron.');
  }
}
